function d(a=[""]){const o=new Set;for(let e of a){const t=e.split(" ");let n=t[t.length-1]||"";if(n.length===1||n.endsWith("."))continue;n.includes("-")&&(n=n.split("-")[0]),n.includes("'")&&(n=n.split("'")[1]);const s=t[0];o.add(`${s} ${n}`)}return Array.from(o)}function A(a,o){if(!o||!String(o).trim())return!0;const e=String(o).trim().toLowerCase(),t=String(a||"").trim().toLowerCase().split(/\s+/).filter(Boolean);if(t.length<2)return!1;const n=t[0],s=t[t.length-1];return n===e||s===e}chrome.runtime.onMessage.addListener((a,o,e)=>{if(a.action==="extractNamesGoogle")return(async()=>{try{if(!a.resume){chrome.storage.local.set({stopGoogleExtraction:!1,googleExtractionState:null,googleCurrentNames:[]})}else{chrome.storage.local.set({stopGoogleExtraction:!1})}const t=await E(a.firstname);if(t&&t.blocked)return e({success:!1,blocked:!0,pageCount:t.pageCount,error:"Google blocked (captcha/unusual traffic)."});e(t===null?{success:!0,navigating:!0}:{success:!0,names:d(t.names),pageCount:t.pageCount})}catch(t){e({success:!1,error:t.message})}})(),!0;if(a.action==="googleCaptchaStatus")return(async()=>{try{return e({success:!0,blocked:Q()})}catch(t){return e({success:!1,error:t.message})}})(),!0;if(a.action==="getGoogleNames")return(async()=>{try{chrome.storage.local.get(["googleCurrentNames"],t=>{const n=t.googleCurrentNames||[];e({success:!0,names:d(n)})})}catch(t){e({success:!1,error:t.message})}})(),!0;if(a.action==="extractNamesContact")return(async()=>{try{chrome.storage.local.set({stopContactExtraction:!1});const t=await N(a.firstname);e({success:!0,names:d(t)})}catch(t){e({success:!1,error:t.message})}})(),!0;if(a.action==="getContactOutNames")return(async()=>{try{chrome.storage.local.get(["contactOutCurrentNames"],t=>{const n=t.contactOutCurrentNames||[];e({success:!0,names:d(n)})})}catch(t){e({success:!1,error:t.message})}})(),!0;if(a.action==="extractNamesContactScrape")return(async()=>{try{chrome.storage.local.set({stopContactScrapeExtraction:!1});const t=await M(a.firstname);e({success:!0,names:d(t)})}catch(t){e({success:!1,error:t.message})}})(),!0;if(a.action==="getContactOutNamesScrape")return(async()=>{try{chrome.storage.local.get(["contactOutCurrentNamesScrape"],t=>{const n=t.contactOutCurrentNamesScrape||[];e({success:!0,names:d(n)})})}catch(t){e({success:!1,error:t.message})}})(),!0;if(a.action==="extractNamesFast")return(async()=>{try{const t=await b(a.firstname);e({success:!0,names:d(t)})}catch(t){e({success:!1,error:t.message})}})(),!0;if(a.action==="copyBarkContent")return(async()=>{try{const t=await S(),n=`${t.title}

Details
${t.details.join(`
`)}

Attachments
${t.attachments.join(`
`)}`;await C(n),e({success:!0,message:"Content extracted and copied to clipboard"})}catch(t){e({success:!1,error:t.message})}})(),!0;if(a.action==="getBarkData")return(async()=>{try{const t=await S(),n=`${t.client} living in ${t.location}; ${t.phone}-`;await C(n),e({success:!0,data:t})}catch{e({success:!1,error:error.message})}})(),!0});async function x(a,o){const e=await new Promise((i,l)=>{chrome.storage.local.get(["apiKey"],r=>{chrome.runtime.lastError?l(chrome.runtime.lastError):i(r.apiKey)})}),n=await(await fetch("https://api.openai.com/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${e}`},body:JSON.stringify({model:"gpt-4o-mini",messages:[{role:"system",content:`
You are an expert at extracting first and last names from plain text. 
Given a block of text and the value "${o}", perform the following steps, returning only the required JSON (do not include code blocks or extra explanation):

1. Find all unique combinations of first and last names where either the first name or last name exactly matches "${o}". Ignore any middle names, initials, prefixes, or suffixes.
2. Standardize each result to "First Last" format (do not include middle names).
3. Output the result as: {"names": ["First Last", ...]}

Return only the JSON object as your output, with no surrounding text or formatting. If there are no matches, return {"names": []}
`},{role:"user",content:a}],temperature:0})})).json();let s=[];try{const l=n.choices[0].message.content.match(/\{[\s\S]*names[\s\S]*\}/);if(l){const r=JSON.parse(l[0]);Array.isArray(r.names)&&(s=r.names)}}catch{}return{names:s}}

function Q(){try{const a=(document.body&&document.body.innerText?document.body.innerText:"").toLowerCase();if(document.querySelector('iframe[src*="recaptcha"]'))return!0;if(document.querySelector("div#g-recaptcha"))return!0;if(document.querySelector('form[action*="sorry"]'))return!0;return a.includes("unusual traffic")||a.includes("our systems have detected unusual traffic")||a.includes("recaptcha")||a.includes("are you a robot")||a.includes("/sorry/")||a.includes("to continue, please type the characters")}catch{return!1}}

async function E(a){const o=await new Promise(c=>{chrome.storage.local.get(["googleExtractionState"],m=>{c(m.googleExtractionState||null)})}),t=o?.pageNum||1;let collectedNames=Array.isArray(o?.collectedNames)?o.collectedNames.slice():[];if(Q())return{blocked:!0,names:[],pageCount:t};const n=[];document.querySelectorAll("#search > div > div > div").forEach(c=>n.push(c.textContent.trim()));const pageText=n.join("\n").trim();const stopNow=await new Promise(c=>{chrome.storage.local.get(["stopGoogleExtraction"],m=>{c(m.stopGoogleExtraction===!0)})});if(pageText){const z=await x(pageText,a);const fresh=z.names||[];collectedNames=d([...collectedNames,...fresh])}async function done(){const i=d(collectedNames);await new Promise(c=>{chrome.storage.local.set({googleExtractionState:null,googleCurrentNames:i},c)});return{names:i,pageCount:t}}if(stopNow)return await done();const r=document.querySelector("a#pnnext");const isLast=!r||r.getAttribute("aria-disabled")==="true"||t>=50;if(isLast)return await done();await new Promise(c=>{chrome.storage.local.set({googleExtractionState:{active:!0,pageNum:t+1,firstname:a,collectedNames}},c)});r.click();return null}chrome.storage.local.get(["googleExtractionState"],async a=>{a.googleExtractionState?.active&&(await new Promise(o=>setTimeout(o,1500)),chrome.storage.local.get(["googleExtractionState","stopGoogleExtraction"],async o=>{if(o.googleExtractionState?.active){const e=await E(o.googleExtractionState.firstname);e&&e.blocked?chrome.runtime.sendMessage({action:"googleExtractionBlocked",pageNum:e.pageCount}):e!==null&&chrome.runtime.sendMessage({action:"googleExtractionComplete",names:d(e.names),pageCount:e.pageCount})}}))});async function N(a){const o=new Set;let e=1;const t=()=>new Promise(n=>{chrome.storage.local.get(["stopContactExtraction"],s=>{n(s.stopContactExtraction===!0)})});for(;e<16;){if(await t()){chrome.storage.local.set({contactOutCurrentNames:Array.from(o)});break}const s=[];document.querySelectorAll(".search-container span.hover\\:underline").forEach(c=>s.push(c.textContent));const{names:l}=await x(s.join(`
`),a);l.forEach(c=>o.add(c)),chrome.storage.local.set({contactOutCurrentNames:Array.from(o)});const r=document.querySelectorAll('div[data-testid="search-pagination"] button')[1];if(!r||r.classList.contains("text-gray-300"))break;if(await t()){chrome.storage.local.set({contactOutCurrentNames:Array.from(o)});break}if(r.click(),e++,await new Promise(u=>setTimeout(u,1e3)),await new Promise(u=>{const h=()=>{chrome.storage.local.get(["stopContactExtraction"],p=>{if(p.stopContactExtraction===!0){chrome.storage.local.set({contactOutCurrentNames:Array.from(o)}),u();return}const g=document.querySelector('button[type="submit"]'),f=document.querySelectorAll('div[data-testid="search-pagination"] button')[1];g&&g.classList.contains("bg-primary-700")||f&&f.classList.contains("text-gray-300")?u():setTimeout(h,200)})};h()}),await t()){chrome.storage.local.set({contactOutCurrentNames:Array.from(o)});break}await new Promise(u=>setTimeout(u,500))}return chrome.storage.local.set({contactOutCurrentNames:[]}),Array.from(o).sort()}

async function M(a){const o=new Set;let e=1;const t=()=>new Promise(n=>{chrome.storage.local.get(["stopContactScrapeExtraction"],s=>{n(s.stopContactScrapeExtraction===!0)})});for(;e<16;){if(await t()){chrome.storage.local.set({contactOutCurrentNamesScrape:Array.from(o)});break}const n=[];document.querySelectorAll(".search-container span.hover\\:underline").forEach(s=>{const l=(s.textContent||"").trim();l&&n.push(l)});for(const s of n)A(s,a)&&o.add(s);chrome.storage.local.set({contactOutCurrentNamesScrape:Array.from(o)});const r=document.querySelectorAll('div[data-testid="search-pagination"] button')[1];if(!r||r.classList.contains("text-gray-300"))break;if(await t()){chrome.storage.local.set({contactOutCurrentNamesScrape:Array.from(o)});break}if(r.click(),e++,await new Promise(u=>setTimeout(u,1e3)),await new Promise(u=>{const h=()=>{chrome.storage.local.get(["stopContactScrapeExtraction"],p=>{if(p.stopContactScrapeExtraction===!0){chrome.storage.local.set({contactOutCurrentNamesScrape:Array.from(o)}),u();return}const g=document.querySelector('button[type="submit"]'),f=document.querySelectorAll('div[data-testid="search-pagination"] button')[1];g&&g.classList.contains("bg-primary-700")||f&&f.classList.contains("text-gray-300")?u():setTimeout(h,200)})};h()}),await t()){chrome.storage.local.set({contactOutCurrentNamesScrape:Array.from(o)});break}await new Promise(u=>setTimeout(u,500))}return chrome.storage.local.set({contactOutCurrentNamesScrape:[]}),Array.from(o).sort()}

async function b(a){const o=new Set,e=[];document.querySelectorAll("span.larger").forEach(s=>e.push(s.textContent));const{names:n}=await x(e.join(`
`),a);return n.forEach(s=>o.add(s)),Array.from(o).sort()}function v(a=""){if(!a)return"";const o={al:"alabama",ak:"alaska",az:"arizona",ar:"arkansas",ca:"california",co:"colorado",ct:"connecticut",de:"delaware",fl:"florida",ga:"georgia",hi:"hawaii",id:"idaho",il:"illinois",in:"indiana",ia:"iowa",ks:"kansas",ky:"kentucky",la:"louisiana",me:"maine",md:"maryland",ma:"massachusetts",mi:"michigan",mn:"minnesota",ms:"mississippi",mo:"missouri",mt:"montana",ne:"nebraska",nv:"nevada",nh:"new hampshire",nj:"new jersey",nm:"new mexico",ny:"new york",nc:"north carolina",nd:"north dakota",oh:"ohio",ok:"oklahoma",or:"oregon",pa:"pennsylvania",ri:"rhode island",sc:"south carolina",sd:"south dakota",tn:"tennessee",tx:"texas",ut:"utah",vt:"vermont",va:"virginia",wa:"washington",wv:"west virginia",wi:"wisconsin",wy:"wyoming","district of columbia":"district of columbia",dc:"district of columbia"},e=a.trim().toLowerCase();if(o[e])return o[e];const t=Object.values(o).find(n=>n===e);return t||e}async function S(){const a={client:"",title:"",location:"",city:"",state:"",phone:"",phonePattern:"",email:"",details:[],attachments:[]};try{const o=document.querySelector(".project-top .project-name-location .buyer_name"),e=document.querySelector(".project-top .project-title"),t=document.querySelector(".project-top .project-name-location .location"),n=document.querySelector(".project-top .buyer-telephone-display"),s=document.querySelector(".project-top .buyer-email-display"),i=document.querySelectorAll(".project-questions-answers > div"),l=[];let r=(t?.textContent||"").trim();r.includes(" (")&&(r=r.split(" (")[0]);const c=r.split(", "),m=c[0]||r,u=v(c[1]||""),h=(n?.textContent||"").trim().replace(/\s+/g," ");a.phonePattern=h,h.includes("(")?a.phone=h.slice(1,4):a.phone=h.replace(/\*/g,"");const p=[];for(let g=0;g<i.length;g++){const f=i[g].textContent.trim();if(i[g].querySelector("a")){const w=i[g].querySelectorAll("a");for(let y=0;y<w.length;y++)l.push(w[y].href)}else f!=="Attachments"&&p.push(f)}return a.title=(e?.textContent||"").trim(),a.client=(o?.textContent||"").trim(),a.email=(s?.textContent||"").trim().toLowerCase(),a.location=r,a.city=m,a.state=u,a.details=p,a.attachments=l,a}catch{return a}}async function C(a){try{await navigator.clipboard.writeText(a)}catch{try{const e=document.createElement("textarea");e.value=a,e.style.position="fixed",e.style.left="-999999px",document.body.appendChild(e),e.select(),document.execCommand("copy"),document.body.removeChild(e)}catch{}}}
